version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: fundset-pg
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
