import './globals.css';
import type { Metadata } from 'next';
import { SettlementLayerProvider } from '@/_fundset/settlement-layer/provider';
import { TanstackQueryProvider } from '@/providers/TanstackQueryProvider';
import { ThemeProvider } from '@/providers/ThemeProvider';
import I18nProvider from '@/providers/I18nProvider';
import { getLocale } from 'next-intl/server';
import { getSettlementLayerConfig } from '@/_fundset/config/getSettlementLayerConfig';
import { ThemeEditor } from '@/features/theme/ThemeEditor';

export const metadata: Metadata = {
  title: 'Fundset 2.0',
  description: 'Generated by create next app',
};

const CSSThemeStyleTag = ({ theme }: { theme: string }) => {
  return <style dangerouslySetInnerHTML={{ __html: theme }} />;
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [locale, { theme, settlementLayerConfigs }] = await Promise.all([
    getLocale(),
    getSettlementLayerConfig(),
  ]);

  return (
    <>
      <html lang={locale} suppressHydrationWarning>
        {theme?.theme && (
          <head>
            <CSSThemeStyleTag theme={theme.theme} />
          </head>
        )}
        <body className={`antialiased`}>
          <I18nProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <TanstackQueryProvider>
                <SettlementLayerProvider configs={settlementLayerConfigs}>
                  {children}
                </SettlementLayerProvider>
              </TanstackQueryProvider>
            </ThemeProvider>
          </I18nProvider>
        </body>
      </html>
      {theme?.editor && <ThemeEditor />}
    </>
  );
}
