import './globals.css';
import type { Metadata } from 'next';
import { SettlementLayerProvider } from '@/_fundset/settlement-layer/provider/index';
import { TanstackQueryProvider } from '@/providers/TanstackQueryProvider';
import { ThemeProvider } from '@/providers/ThemeProvider';
import I18nProvider from '@/providers/I18nProvider';
import { getSettlementLayerConfig } from '@/_fundset/config/getSettlementLayerConfig';
import { ThemeEditor } from '@/features/theme/ThemeEditor';
import { routing } from '@/i18n/routing';
import { Locale } from 'next-intl';

export const metadata: Metadata = {
  title: 'Fundset 2.0',
  description: 'Generated by create next app',
};

const CSSThemeStyleTag = ({ theme }: { theme: string }) => {
  return <style dangerouslySetInnerHTML={{ __html: theme }} />;
};

export const generateStaticParams = async () => {
  return routing.locales.map(locale => ({ locale }));
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { theme, settlementLayerConfigs } = await getSettlementLayerConfig();
  const locale = ((await params).locale ?? routing.defaultLocale) as Locale;

  return (
    <>
      <html lang={locale} suppressHydrationWarning>
        {theme?.theme && (
          <head>
            <CSSThemeStyleTag theme={theme.theme} />
          </head>
        )}
        <body className={`antialiased`}>
          <I18nProvider locale={locale}>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <TanstackQueryProvider>
                <SettlementLayerProvider configs={settlementLayerConfigs}>
                  {children}
                </SettlementLayerProvider>
              </TanstackQueryProvider>
            </ThemeProvider>
          </I18nProvider>
        </body>
      </html>
      {theme?.editor && <ThemeEditor />}
    </>
  );
}
