// this file was automatically generated by @solidstate/hardhat-abi-exporter - do not modify
export default [
  {
    "type": "function",
    "name": "CounterStorageLocation",
    "constant": true,
    "stateMutability": "view",
    "payable": false,
    "inputs": [],
    "outputs": [
      {
        "type": "bytes32"
      }
    ]
  }
] as const;
