// this file was automatically generated by @solidstate/hardhat-abi-exporter - do not modify
export default [
  {
    "type": "error",
    "name": "DiamondWritable__InvalidInitializationParameters",
    "inputs": []
  },
  {
    "type": "error",
    "name": "DiamondWritable__RemoveTargetNotZeroAddress",
    "inputs": []
  },
  {
    "type": "error",
    "name": "DiamondWritable__ReplaceTargetIsIdentical",
    "inputs": []
  },
  {
    "type": "error",
    "name": "DiamondWritable__SelectorAlreadyAdded",
    "inputs": []
  },
  {
    "type": "error",
    "name": "DiamondWritable__SelectorIsImmutable",
    "inputs": []
  },
  {
    "type": "error",
    "name": "DiamondWritable__SelectorNotFound",
    "inputs": []
  },
  {
    "type": "error",
    "name": "DiamondWritable__SelectorNotSpecified",
    "inputs": []
  },
  {
    "type": "error",
    "name": "DiamondWritable__TargetHasNoCode",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ERC165Base__InvalidInterfaceId",
    "inputs": []
  },
  {
    "type": "error",
    "name": "Ownable__NotOwner",
    "inputs": []
  },
  {
    "type": "error",
    "name": "Ownable__NotTransitiveOwner",
    "inputs": []
  },
  {
    "type": "error",
    "name": "Proxy__ImplementationIsNotContract",
    "inputs": []
  },
  {
    "type": "error",
    "name": "SafeOwnable__NotNomineeOwner",
    "inputs": []
  },
  {
    "type": "event",
    "anonymous": false,
    "name": "DiamondCut",
    "inputs": [
      {
        "type": "tuple[]",
        "name": "facetCuts",
        "indexed": false,
        "components": [
          {
            "type": "address",
            "name": "target"
          },
          {
            "type": "uint8",
            "name": "action"
          },
          {
            "type": "bytes4[]",
            "name": "selectors"
          }
        ]
      },
      {
        "type": "address",
        "name": "target",
        "indexed": false
      },
      {
        "type": "bytes",
        "name": "data",
        "indexed": false
      }
    ]
  },
  {
    "type": "event",
    "anonymous": false,
    "name": "OwnershipTransferred",
    "inputs": [
      {
        "type": "address",
        "name": "previousOwner",
        "indexed": true
      },
      {
        "type": "address",
        "name": "newOwner",
        "indexed": true
      }
    ]
  },
  {
    "type": "function",
    "name": "acceptOwnership",
    "constant": false,
    "payable": false,
    "inputs": [],
    "outputs": []
  },
  {
    "type": "function",
    "name": "diamondCut",
    "constant": false,
    "payable": false,
    "inputs": [
      {
        "type": "tuple[]",
        "name": "facetCuts",
        "components": [
          {
            "type": "address",
            "name": "target"
          },
          {
            "type": "uint8",
            "name": "action"
          },
          {
            "type": "bytes4[]",
            "name": "selectors"
          }
        ]
      },
      {
        "type": "address",
        "name": "target"
      },
      {
        "type": "bytes",
        "name": "data"
      }
    ],
    "outputs": []
  },
  {
    "type": "function",
    "name": "facetAddress",
    "constant": true,
    "stateMutability": "view",
    "payable": false,
    "inputs": [
      {
        "type": "bytes4",
        "name": "selector"
      }
    ],
    "outputs": [
      {
        "type": "address",
        "name": "facet"
      }
    ]
  },
  {
    "type": "function",
    "name": "facetAddresses",
    "constant": true,
    "stateMutability": "view",
    "payable": false,
    "inputs": [],
    "outputs": [
      {
        "type": "address[]",
        "name": "addresses"
      }
    ]
  },
  {
    "type": "function",
    "name": "facetFunctionSelectors",
    "constant": true,
    "stateMutability": "view",
    "payable": false,
    "inputs": [
      {
        "type": "address",
        "name": "facet"
      }
    ],
    "outputs": [
      {
        "type": "bytes4[]",
        "name": "selectors"
      }
    ]
  },
  {
    "type": "function",
    "name": "facets",
    "constant": true,
    "stateMutability": "view",
    "payable": false,
    "inputs": [],
    "outputs": [
      {
        "type": "tuple[]",
        "name": "diamondFacets",
        "components": [
          {
            "type": "address",
            "name": "target"
          },
          {
            "type": "bytes4[]",
            "name": "selectors"
          }
        ]
      }
    ]
  },
  {
    "type": "function",
    "name": "getFallbackAddress",
    "constant": true,
    "stateMutability": "view",
    "payable": false,
    "inputs": [],
    "outputs": [
      {
        "type": "address",
        "name": "fallbackAddress"
      }
    ]
  },
  {
    "type": "function",
    "name": "nomineeOwner",
    "constant": true,
    "stateMutability": "view",
    "payable": false,
    "inputs": [],
    "outputs": [
      {
        "type": "address"
      }
    ]
  },
  {
    "type": "function",
    "name": "owner",
    "constant": true,
    "stateMutability": "view",
    "payable": false,
    "inputs": [],
    "outputs": [
      {
        "type": "address"
      }
    ]
  },
  {
    "type": "function",
    "name": "setFallbackAddress",
    "constant": false,
    "payable": false,
    "inputs": [
      {
        "type": "address",
        "name": "fallbackAddress"
      }
    ],
    "outputs": []
  },
  {
    "type": "function",
    "name": "supportsInterface",
    "constant": true,
    "stateMutability": "view",
    "payable": false,
    "inputs": [
      {
        "type": "bytes4",
        "name": "interfaceId"
      }
    ],
    "outputs": [
      {
        "type": "bool"
      }
    ]
  },
  {
    "type": "function",
    "name": "transferOwnership",
    "constant": false,
    "payable": false,
    "inputs": [
      {
        "type": "address",
        "name": "account"
      }
    ],
    "outputs": []
  }
] as const;
