export const ERROR_CODES = {
  TX_REJECTED_BY_USER: 'TX_REJECTED_BY_USER',
  FAILED_TO_SWITCH_TO_REQUIRED_NETWORK: 'FAILED_TO_SWITCH_TO_REQUIRED_NETWORK',
  INSUFFICIENT_FUNDS: 'INSUFFICIENT_FUNDS',
  CONTRACT_EXECUTION_FAILED: 'CONTRACT_EXECUTION_FAILED',
  CONTRACT_FUNCTION_REVERTED: 'CONTRACT_FUNCTION_REVERTED',
  TX_REJECTED_BY_NETWORK: 'TX_REJECTED_BY_NETWORK',
  TRANSACTION_CONFIRMATION_TIMED_OUT: 'TRANSACTION_CONFIRMATION_TIMED_OUT',
  RPC_REQUEST_FAILED: 'RPC_REQUEST_FAILED',
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
};
